### PR TITLE
Universal quirks

### PR DESCRIPTION
**Pull request by JacKeTUs**
Changes to initialization
Now naming driver not as "Moza", but "Universal driver for steering wheels", and moving every quirk vendor/device has to the quirks

With that we can implement Cammus or VRS support right here

### CODE REVIEW

**Comment by JacKeTUs** [comment]
@Lawstorant, may be you will be interested in testing this

**Comment by JacKeTUs** [comment]
In conversation in Matrix chat, there was quote from @berarma

> The translation from Linux API to HID PID is clear, 0 -> ffff. If later some device appears which uses 1234 instead of ffff, we implement a quirk for that device which doesn't follow the HID PID spec.

So we don't need quirk for that, i will remove it

**Comment by Lawstorant** [comment]
I didn't have much time in the past week, but I'll try just doing small smoke test today

**Comment by Lawstorant** [comment]
Hmm, give ma another day or two. I did some fixes on the main branch of moza-ff to enable further effects. I'd have to rebase my work on top of this branch

**Pull request merged**
