### PR TITLE
Added signing section to the README

### PR DESCRIPTION
**Pull request by JacKeTUs**

### CODE REVIEW

**Review by cjhelloletsgo — COMMENTED** [review]
@JacKeTUs It looks accurate from what I see. My only nitpick is that on line 21 and 37 "greated" should be "greeted"

**Comment by JacKeTUs** [comment]
@cjhelloletsgo, thanks!
Can you please try to follow automatic signing procedure? Enroll DKMS's autogenerated MOK key into the machine, and reinstall module through DKMS? It should work fine, but i'd like to double check

**Comment by cjhelloletsgo** [comment]
Yes, I will give it a shot later today!

**Comment by cjhelloletsgo** [comment]
Ok, I have a few notes.

Firstly for me at least there were no files in the /var/lib/dkms/ directory, the default location appears to be /var/lib/shim-signed/mok/ It actually mentions that in your dkms reference link as well. I'm not sure if the file path might be different on different distros but I am on Ubuntu 24.04 if it matters. 

So with that in mind for me it worked like this:

confirm keys are present (keys for me were uppercase)
```
ls -al /var/lib/shim-signed/mok/MOK*
```
Screenshot from 2024-07-18 20-10-37

Apparently you can just import .der files? I ran 
```
sudo mokutil --import /var/lib/shim-signed/mok/MOK.der
```
 then  input my password, rebooted, added the key when it booted then ran 

```
sudo dkms install /usr/src/universal-pidff
```
and 
```
sudo update-initramfs -u
```
then tried
```
sudo dmesg | grep hid-universal-pidff
```
to check if the driver was loaded and nothing, so I rebooted and tried again and then it says the driver is loaded and ff was working again.

**Comment by JacKeTUs** [comment]
> I'm not sure if the file path might be different on different distros but I am on Ubuntu 24.04 if it matters.

Looks like it, on Ubuntu keys are generated at different path. Well, i updated instructions with that info :D

**Comment by cjhelloletsgo** [comment]
With that change both methods are accurate from my perspective.

**Pull request merged**
