### PR TITLE
Added Cammus C5

### PR DESCRIPTION
**Pull request by JacKeTUs**
Cammus C5 wheelbase should work now

### CODE REVIEW

**Comment by JacKeTUs** [comment]
@spikerguy, please, test this branch on your Cammus wheel :pray: 
After successful tests we can archive cammus-ff repo and move users to this 'unversal' driver

**Comment by spikerguy** [comment]
Hey @JacKeTUs 

```
[  109.250510] usb 1-2.2.1: new full-speed USB device number 10 using xhci_hcd
[  109.371860] usb 1-2.2.1: not running at top speed; connect to a high speed hub
[  109.383858] usb 1-2.2.1: New USB device found, idVendor=1a86, idProduct=8091, bcdDevice= 2.10
[  109.383863] usb 1-2.2.1: New USB device strings: Mfr=0, Product=2, SerialNumber=0
[  109.383866] usb 1-2.2.1: Product: USB HUB
[  109.435924] hub 1-2.2.1:1.0: USB hub found
[  109.438878] hub 1-2.2.1:1.0: 4 ports detected
[  109.747233] usb 1-2.2.1.1: new full-speed USB device number 11 using xhci_hcd
[  109.897907] usb 1-2.2.1.1: New USB device found, idVendor=8587, idProduct=5757, bcdDevice= 2.00
[  109.897919] usb 1-2.2.1.1: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[  109.897925] usb 1-2.2.1.1: Product: JACK-SQ
[  109.897929] usb 1-2.2.1.1: Manufacturer: FreeJoy
[  110.011997] [284] drivers/hid/usbhid/hid-core.c: HID probe called for ifnum 0
[  110.034185] input: FreeJoy JACK-SQ as /devices/pci0000:00/0000:00:08.1/0000:c5:00.3/usb1/1-2/1-2.2/1-2.2.1/1-2.2.1.1/1-2.2.1.1:1.0/0003:8587:5757.0009/input/input18
[  110.034411] [284] hid-generic 0003:8587:5757.0009: starting pid init
[  110.034418] [284] hid-generic 0003:8587:5757.0009: not a PID device, no output report
[  110.034425] hid-generic 0003:8587:5757.0009: input,hidraw8: USB HID v1.10 Joystick [FreeJoy JACK-SQ] on usb-0000:c5:00.3-2.2.1.1/input0
[  110.034547] [284] drivers/hid/usbhid/hid-core.c: HID probe called for ifnum 1
[  110.056505] hid-generic 0003:8587:5757.000A: hiddev97,hidraw9: USB HID v1.10 Device [FreeJoy JACK-SQ] on usb-0000:c5:00.3-2.2.1.1/input1
[  110.277247] usb 1-2.2.1.2: new full-speed USB device number 12 using xhci_hcd
[  110.409913] usb 1-2.2.1.2: New USB device found, idVendor=3416, idProduct=0301, bcdDevice= 2.00
[  110.409925] usb 1-2.2.1.2: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[  110.409931] usb 1-2.2.1.2: Product: CAMMUS C5 Base
[  110.409935] usb 1-2.2.1.2: Manufacturer: CAMMUS
[  110.409939] usb 1-2.2.1.2: SerialNumber: 1669827171
[  110.529976] cdc_acm 1-2.2.1.2:1.0: ttyACM1: USB ACM device
[  110.532930] [284] drivers/hid/usbhid/hid-core.c: HID probe called for ifnum 2
[  110.542818] input: CAMMUS CAMMUS C5 Base as /devices/pci0000:00/0000:00:08.1/0000:c5:00.3/usb1/1-2/1-2.2/1-2.2.1/1-2.2.1.2/1-2.2.1.2:1.2/0003:3416:0301.000B/input/input19
[  110.543075] [284] hid-generic 0003:3416:0301.000B: starting pid init
[  110.543081] [284] hid-generic 0003:3416:0301.000B: found usage 0x21 from field->logical
[  110.543086] [284] hid-generic 0003:3416:0301.000B: found usage 0x5a from field->logical
[  110.543090] [284] hid-generic 0003:3416:0301.000B: found usage 0x5f from field->logical
[  110.543094] [284] hid-generic 0003:3416:0301.000B: found usage 0x6e from field->logical
[  110.543098] [284] hid-generic 0003:3416:0301.000B: found usage 0x73 from field->logical
[  110.543101] [284] hid-generic 0003:3416:0301.000B: found usage 0x74 from field->logical
[  110.543106] [284] hid-generic 0003:3416:0301.000B: found usage 0x77 from field->logical
[  110.543109] [284] hid-generic 0003:3416:0301.000B: found usage 0x90 from field->logical
[  110.543113] [284] hid-generic 0003:3416:0301.000B: found usage 0x96 from field->logical
[  110.543117] [284] hid-generic 0003:3416:0301.000B: found usage 0x7d from field->logical
[  110.543121] [284] hid-generic 0003:3416:0301.000B: found usage 0xab from collection array
[  110.543125] [284] hid-generic 0003:3416:0301.000B: found usage 0x89 from field->logical
[  110.543128] [284] hid-generic 0003:3416:0301.000B: found usage 0x7f from field->logical
[  110.543132] [284] usbhid: found 0 at 0->0
[  110.543137] [284] usbhid: maxusage and report_count do not match, skipping
[  110.543140] [284] usbhid: found 1 at 2->0
[  110.543143] [284] usbhid: maxusage and report_count do not match, skipping
[  110.543146] [284] usbhid: found 2 at 3->0
[  110.543149] [284] usbhid: maxusage and report_count do not match, skipping
[  110.543152] [284] usbhid: found 3 at 4->0
[  110.543155] [284] usbhid: maxusage and report_count do not match, skipping
[  110.543158] [284] usbhid: found 4 at 2->1
[  110.543161] [284] usbhid: maxusage and report_count do not match, skipping
[  110.543164] [284] usbhid: found 5 at 6->0
[  110.543167] [284] usbhid: maxusage and report_count do not match, skipping
[  110.543170] [284] usbhid: failed to locate 6
[  110.543174] hid-generic 0003:3416:0301.000B: unknown set_effect report layout
[  110.543194] hid-generic 0003:3416:0301.000B: input,hiddev98,hidraw10: USB HID v1.11 Gamepad [CAMMUS CAMMUS C5 Base] on usb-0000:c5:00.3-2.2.1.2/input2
[  110.575802] hid_universal_pidff: loading out-of-tree module taints kernel.
[  110.575809] hid_universal_pidff: module verification failed: signature and/or required key missing - tainting kernel
[  110.678205] input: CAMMUS CAMMUS C5 Base as /devices/pci0000:00/0000:00:08.1/0000:c5:00.3/usb1/1-2/1-2.2/1-2.2.1/1-2.2.1.2/1-2.2.1.2:1.2/0003:3416:0301.000B/input/input21
[  110.678401] hid-universal-pidff 0003:3416:0301.000B: input,hiddev98,hidraw10: USB HID v1.11 Gamepad [CAMMUS CAMMUS C5 Base] on usb-0000:c5:00.3-2.2.1.2/input2
[  110.678410] hid-universal-pidff 0003:3416:0301.000B: unknown set_effect report layout
[  110.678413] hid-universal-pidff 0003:3416:0301.000B: Force feedback not supported
[  113.053841] usb 1-2.2.1.3: new full-speed USB device number 13 using xhci_hcd
[  113.186894] usb 1-2.2.1.3: New USB device found, idVendor=3416, idProduct=1021, bcdDevice= 2.00
[  113.186901] usb 1-2.2.1.3: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[  113.186905] usb 1-2.2.1.3: Product: Cammus_C5_HUB_V002 Buttons
[  113.186907] usb 1-2.2.1.3: Manufacturer: Cammus_C5_HUB_V0013
[  113.186909] usb 1-2.2.1.3: SerialNumber: 497232613448
[  113.275944] [106] drivers/hid/usbhid/hid-core.c: HID probe called for ifnum 0
[  113.284006] Cammus_C5_HUB_V0013 Cammus_C5_HUB_V002 Buttons: Invalid code 768 type 1
[  113.284009] Cammus_C5_HUB_V0013 Cammus_C5_HUB_V002 Buttons: Invalid code 769 type 1
[  113.284011] Cammus_C5_HUB_V0013 Cammus_C5_HUB_V002 Buttons: Invalid code 770 type 1
[  113.284013] Cammus_C5_HUB_V0013 Cammus_C5_HUB_V002 Buttons: Invalid code 771 type 1
[  113.284015] Cammus_C5_HUB_V0013 Cammus_C5_HUB_V002 Buttons: Invalid code 772 type 1
[  113.284016] Cammus_C5_HUB_V0013 Cammus_C5_HUB_V002 Buttons: Invalid code 773 type 1
[  113.284018] Cammus_C5_HUB_V0013 Cammus_C5_HUB_V002 Buttons: Invalid code 774 type 1
[  113.284019] Cammus_C5_HUB_V0013 Cammus_C5_HUB_V002 Buttons: Invalid code 775 type 1
[  113.284021] Cammus_C5_HUB_V0013 Cammus_C5_HUB_V002 Buttons: Invalid code 776 type 1
[  113.284023] Cammus_C5_HUB_V0013 Cammus_C5_HUB_V002 Buttons: Invalid code 777 type 1
[  113.284099] input: Cammus_C5_HUB_V0013 Cammus_C5_HUB_V002 Buttons as /devices/pci0000:00/0000:00:08.1/0000:c5:00.3/usb1/1-2/1-2.2/1-2.2.1/1-2.2.1.3/1-2.2.1.3:1.0/0003:3416:1021.000C/input/input22
[  113.284248] [106] hid-generic 0003:3416:1021.000C: starting pid init
[  113.284251] [106] hid-generic 0003:3416:1021.000C: 0 missing
[  113.284254] [106] hid-generic 0003:3416:1021.000C: reports not ok, aborting
[  113.284258] hid-generic 0003:3416:1021.000C: input,hidraw11: USB HID v1.11 Joystick [Cammus_C5_HUB_V0013 Cammus_C5_HUB_V002 Buttons] on usb-0000:c5:00.3-2.2.1.3/input0
```

**Comment by JacKeTUs** [comment]
found out why, need to wait for https://github.com/JacKeTUs/universal-pidff/pull/12 to merge

**Comment by JacKeTUs** [comment]
@spikerguy, initialization fixed, please test again

**Comment by spikerguy** [comment]
@JacKeTUs 

```
[   74.998133] usb 1-2.2.1: new full-speed USB device number 10 using xhci_hcd
[   75.116094] usb 1-2.2.1: not running at top speed; connect to a high speed hub
[   75.128098] usb 1-2.2.1: New USB device found, idVendor=1a86, idProduct=8091, bcdDevice= 2.10
[   75.128105] usb 1-2.2.1: New USB device strings: Mfr=0, Product=2, SerialNumber=0
[   75.128109] usb 1-2.2.1: Product: USB HUB
[   75.181198] hub 1-2.2.1:1.0: USB hub found
[   75.184102] hub 1-2.2.1:1.0: 4 ports detected
[   75.494800] usb 1-2.2.1.2: new full-speed USB device number 11 using xhci_hcd
[   75.617107] usb 1-2.2.1.2: New USB device found, idVendor=3416, idProduct=0301, bcdDevice= 2.00
[   75.617119] usb 1-2.2.1.2: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[   75.617125] usb 1-2.2.1.2: Product: CAMMUS C5 Base
[   75.617129] usb 1-2.2.1.2: Manufacturer: CAMMUS
[   75.617133] usb 1-2.2.1.2: SerialNumber: 1669827171
[   75.731248] cdc_acm 1-2.2.1.2:1.0: ttyACM1: USB ACM device
[   75.734138] [318] drivers/hid/usbhid/hid-core.c: HID probe called for ifnum 2
[   75.744162] input: CAMMUS CAMMUS C5 Base as /devices/pci0000:00/0000:00:08.1/0000:c5:00.3/usb1/1-2/1-2.2/1-2.2.1/1-2.2.1.2/1-2.2.1.2:1.2/0003:3416:0301.0009/input/input18
[   75.744840] [318] hid-generic 0003:3416:0301.0009: starting pid init
[   75.744850] [318] hid-generic 0003:3416:0301.0009: found usage 0x21 from field->logical
[   75.744858] [318] hid-generic 0003:3416:0301.0009: found usage 0x5a from field->logical
[   75.744864] [318] hid-generic 0003:3416:0301.0009: found usage 0x5f from field->logical
[   75.744870] [318] hid-generic 0003:3416:0301.0009: found usage 0x6e from field->logical
[   75.744875] [318] hid-generic 0003:3416:0301.0009: found usage 0x73 from field->logical
[   75.744881] [318] hid-generic 0003:3416:0301.0009: found usage 0x74 from field->logical
[   75.744887] [318] hid-generic 0003:3416:0301.0009: found usage 0x77 from field->logical
[   75.744893] [318] hid-generic 0003:3416:0301.0009: found usage 0x90 from field->logical
[   75.744898] [318] hid-generic 0003:3416:0301.0009: found usage 0x96 from field->logical
[   75.744904] [318] hid-generic 0003:3416:0301.0009: found usage 0x7d from field->logical
[   75.744910] [318] hid-generic 0003:3416:0301.0009: found usage 0xab from collection array
[   75.744916] [318] hid-generic 0003:3416:0301.0009: found usage 0x89 from field->logical
[   75.744921] [318] hid-generic 0003:3416:0301.0009: found usage 0x7f from field->logical
[   75.744924] [318] usbhid: found 0 at 0->0
[   75.744928] [318] usbhid: maxusage and report_count do not match, skipping
[   75.744929] [318] usbhid: found 1 at 2->0
[   75.744931] [318] usbhid: maxusage and report_count do not match, skipping
[   75.744932] [318] usbhid: found 2 at 3->0
[   75.744934] [318] usbhid: maxusage and report_count do not match, skipping
[   75.744935] [318] usbhid: found 3 at 4->0
[   75.744937] [318] usbhid: maxusage and report_count do not match, skipping
[   75.744939] [318] usbhid: found 4 at 2->1
[   75.744940] [318] usbhid: maxusage and report_count do not match, skipping
[   75.744941] [318] usbhid: found 5 at 6->0
[   75.744942] [318] usbhid: maxusage and report_count do not match, skipping
[   75.744943] [318] usbhid: failed to locate 6
[   75.744944] hid-generic 0003:3416:0301.0009: unknown set_effect report layout
[   75.744947] hid-generic 0003:3416:0301.0009: input,hiddev97,hidraw8: USB HID v1.11 Gamepad [CAMMUS CAMMUS C5 Base] on usb-0000:c5:00.3-2.2.1.2/input2
[   75.780750] hid_universal_pidff: loading out-of-tree module taints kernel.
[   75.780755] hid_universal_pidff: module verification failed: signature and/or required key missing - tainting kernel
[   75.865705] input: CAMMUS CAMMUS C5 Base as /devices/pci0000:00/0000:00:08.1/0000:c5:00.3/usb1/1-2/1-2.2/1-2.2.1/1-2.2.1.2/1-2.2.1.2:1.2/0003:3416:0301.0009/input/input20
[   75.865979] hid-universal-pidff 0003:3416:0301.0009: input,hiddev97,hidraw8: USB HID v1.11 Gamepad [CAMMUS CAMMUS C5 Base] on usb-0000:c5:00.3-2.2.1.2/input2
[   75.865988] hid-universal-pidff 0003:3416:0301.0009: implement() called with too large value 4 (n: 1)! ((udev-worker))
[   75.865993] [4755] hid-universal-pidff 0003:3416:0301.0009: Kicking head 1 tail 0
[   75.865996] [4755] drivers/hid/usbhid/hid-core.c: submitting out urb
[   75.867300] hid-universal-pidff 0003:3416:0301.0009: implement() called with too large value 4 (n: 1)! ((udev-worker))
[   75.867302] [4755] hid-universal-pidff 0003:3416:0301.0009: Kicking head 2 tail 1
[   75.867303] [4755] drivers/hid/usbhid/hid-core.c: submitting out urb
[   75.868302] [4755] hid-universal-pidff 0003:3416:0301.0009: Kicking head 3 tail 2
[   75.868303] [4755] drivers/hid/usbhid/hid-core.c: submitting out urb
[   75.869311] [4755] hid-universal-pidff 0003:3416:0301.0009: Kicking head 1 tail 0
[   75.869314] [4755] drivers/hid/usbhid/hid-core.c: submitting ctrl urb: Get_Report wValue=0x0313 wIndex=0x0002 wLength=64
[   75.871072] [4755] hid-universal-pidff 0003:3416:0301.0009: Kicking head 4 tail 3
[   75.871074] [4755] drivers/hid/usbhid/hid-core.c: submitting out urb
[   75.871078] [4755] hid-universal-pidff 0003:3416:0301.0009: Kicking head 2 tail 1
[   75.871080] [4755] drivers/hid/usbhid/hid-core.c: submitting ctrl urb: Set_Report wValue=0x0311 wIndex=0x0002 wLength=4
[   75.874064] [4755] hid-universal-pidff 0003:3416:0301.0009: Kicking head 3 tail 2
[   75.874067] [4755] drivers/hid/usbhid/hid-core.c: submitting ctrl urb: Get_Report wValue=0x0312 wIndex=0x0002 wLength=64
[   75.877101] hid-universal-pidff 0003:3416:0301.0009: device has unknown autocenter control method
[   75.877105] [4755] hid-universal-pidff 0003:3416:0301.0009: Kicking head 5 tail 4
[   75.877107] [4755] drivers/hid/usbhid/hid-core.c: submitting out urb
[   75.877127] input input20: Force feedback for USB HID PID devices
[   78.371486] usb 1-2.2.1.3: new full-speed USB device number 12 using xhci_hcd
[   78.501063] usb 1-2.2.1.3: New USB device found, idVendor=3416, idProduct=1021, bcdDevice= 2.00
[   78.501071] usb 1-2.2.1.3: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[   78.501074] usb 1-2.2.1.3: Product: Cammus_C5_HUB_V002 Buttons
[   78.501076] usb 1-2.2.1.3: Manufacturer: Cammus_C5_HUB_V0018
[   78.501079] usb 1-2.2.1.3: SerialNumber: 497232613448
[   78.573184] [643] drivers/hid/usbhid/hid-core.c: HID probe called for ifnum 0
[   78.581186] Cammus_C5_HUB_V0018 Cammus_C5_HUB_V002 Buttons: Invalid code 768 type 1
[   78.581191] Cammus_C5_HUB_V0018 Cammus_C5_HUB_V002 Buttons: Invalid code 769 type 1
[   78.581193] Cammus_C5_HUB_V0018 Cammus_C5_HUB_V002 Buttons: Invalid code 770 type 1
[   78.581195] Cammus_C5_HUB_V0018 Cammus_C5_HUB_V002 Buttons: Invalid code 771 type 1
[   78.581197] Cammus_C5_HUB_V0018 Cammus_C5_HUB_V002 Buttons: Invalid code 772 type 1
[   78.581198] Cammus_C5_HUB_V0018 Cammus_C5_HUB_V002 Buttons: Invalid code 773 type 1
[   78.581200] Cammus_C5_HUB_V0018 Cammus_C5_HUB_V002 Buttons: Invalid code 774 type 1
[   78.581202] Cammus_C5_HUB_V0018 Cammus_C5_HUB_V002 Buttons: Invalid code 775 type 1
[   78.581203] Cammus_C5_HUB_V0018 Cammus_C5_HUB_V002 Buttons: Invalid code 776 type 1
[   78.581205] Cammus_C5_HUB_V0018 Cammus_C5_HUB_V002 Buttons: Invalid code 777 type 1
[   78.581284] input: Cammus_C5_HUB_V0018 Cammus_C5_HUB_V002 Buttons as /devices/pci0000:00/0000:00:08.1/0000:c5:00.3/usb1/1-2/1-2.2/1-2.2.1/1-2.2.1.3/1-2.2.1.3:1.0/0003:3416:1021.000A/input/input21
[   78.581545] [643] hid-generic 0003:3416:1021.000A: starting pid init
[   78.581550] [643] hid-generic 0003:3416:1021.000A: 0 missing
[   78.581554] [643] hid-generic 0003:3416:1021.000A: reports not ok, aborting
[   78.581560] hid-generic 0003:3416:1021.000A: input,hidraw9: USB HID v1.11 Joystick [Cammus_C5_HUB_V0018 Cammus_C5_HUB_V002 Buttons] on usb-0000:c5:00.3-2.2.1.3/input0
```

Check this

**Pull request merged**
